# Generated by Django 4.0.3 on 2022-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('city', models.EmailField(max_length=50)),
                ('proposed_firm', models.CharField(max_length=50)),
                ('gst_no', models.EmailField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_holder', models.CharField(max_length=20)),
            ],
        ),
    ]
