# Generated by Django 4.0.3 on 2022-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('speed_desc', models.CharField(max_length=50)),
                ('max_speed', models.CharField(max_length=50)),
                ('max_speed_dec', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
